services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - unix_socket:/tmp/  # Shared UNIX socket for uWSGI and nginx
      - static:/app/staticfiles
    networks:
      - backend
    env_file:
      - ./.env
    command: uwsgi --ini /app/uwsgi/uwsgi.ini  # Use uwsgi.ini for uWSGI configuration

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile.nginx
    ports:
      - "443:443"
      - "80:80"  # Expose HTTP port
    volumes:
      - unix_socket:/tmp/  # Shared UNIX socket
      - static:/app/staticfiles
    depends_on:
      - django
    networks:
      - backend

networks:
  backend:

volumes:
  unix_socket:
  static:
