services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - unix_socket:/tmp/
      - static:/app/staticfiles
    networks:
      - backend
    env_file:
      - ./.env
    depends_on:
      - pgbouncer
      - redis
    command: uwsgi --ini /app/uwsgi/uwsgi.ini

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - unix_socket:/tmp/
      - static:/app/staticfiles
    depends_on:
      - django
    networks:
      - backend
      
  postgres_db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - backend
      
  pgbouncer:
    build:
      context: ./pgbouncer
      dockerfile: Dockerfile.pgbouncer
      args:
        PG_USER: ${POSTGRES_USER}
        PG_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "6432:6432"
    env_file:
      - ./.env
    depends_on:
      - postgres_db
    networks:
      - backend
      
  mongo_db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    networks:
      - backend 
      
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile.redis
    ports:
      - "6379:6379"
    networks:
      - backend
    env_file:
      - ./.env

networks:
  backend:

volumes:
  unix_socket:
  static:
  postgres_data:
  mongo_data:
  redis_data: